# Generated by Django 4.2.18 on 2025-01-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
